---
title: "R과 파이썬 정리"
output: html_notebook
---

## 1.0 파이썬과 R 정리

### 서론

파이썬도 RStudio에서 지원해주는것 같기는 한데 예전에 사용할때 vscode에서 단계별로 실행한 기억이 있는데 다시해보니 느낌에 차이가 나는듯 해서 R Studio를 파이썬도 스터디 용도로 사용해본다.

**장점**으로는 R과 파이썬 둘다 코드를 바로바로 작성해서 테스트가 가능한것으로 보임.

### 파이썬 패키지 설치

-   cmd창에서 실행해야한다.
    > | \> python –m pip install –upgrade pip
    > | \> pip3 install mglearn
    > | \> pip3 install graphviz


#### import libraries
```{python eval=F}
# 'generic import' of math module
import math 
ret1 = math.sqrt(25)
# import a function from math 
from math import sqrt
ret1 = sqrt(25) 
# import multiple functions at once from math 
from math import cos, floor
import os
path1 = os.getcwd() # in R, getwd()
os.chdir('data') # in R, setwd(“c:/data/rdata”)
os.chdir('..')
# print(os.getcwd())
import pandas as pd
bmi = pd.read_csv('data/auto.csv')
```

#### comment
```{python eval=F}
# comments in line
'''
Comments in sentences
Brian Heinold, A Practical Introduction to Python Programming, 2012.
Edouard Duchesnay, Tommy Löfstedt. Statistics and Machine Learning in Python, 
2018.
'''
help('modules') # 설치된 모듈 목록 보기
```


#### basic operations
```{python eval=F}
# number
r1 = 10**3 # 1000
r2 = 10/4 # # 2.5
r3 = 10/float(4) # 2.5
r4 = 5 %4  # modulo 1
r5 = 10 // 4 # floor division 2

# Boolean operations
# comparisons (these return True)
5 > 3
5 >= 3
5 != 3
5 == 5
# boolean operations (these return True)
5 > 3 & 6 > 3 # 5 > 3 and 6 > 3 
5 > 3 | 5 < 3 # 5 > 3 or 5 < 3
!FALSE # not False
FALSE | !FALSE & TRUE # False or not False and True
```


#### Data type
```{python eval=F}

# determine the type of an object 
type(2) # returns 'int' 
type(2.0) # returns 'float' 
type('two') # returns 'str' 
type(True) # returns 'bool' 
type(None) # returns 'NoneType'
# check if an object is of a given type 
isinstance(2.0, int) # returns False 
isinstance(2.0, (int, float)) # returns True
# convert an object to a given type 
float(2) 
int(2.9) 
str(2.9)
# zero, None, and empty containers are converted to False 
bool(0) 
bool(None)
bool('') # empty string 
bool([]) # empty list 
bool({}) # empty dictionary

```

#### Tuples, lists and dictionaries
The 3 basic data types in Python are :  
__- Tuples – List - Dictionary__ 

**Tuples**: Tuples are immutable python objects which are enclosed with paranthesis. Immutability implies 
that objects cannot be added or removed to tuples. Hence we cannot
add or remove elements from tuples. However a tuple can be removed using the del() commands  

**List**: List are a sequence of disimilar objects enclosed within square brackets. Objects
can be added to lists using append() and deleted using remove()  

**Dictionary**: Dictionaries are a name(key)-value pair enclosed within curly braces. The name- value 
pairs are separated using a ':'. The keys must be unique in the dictionary
The length of tuples, lists and dictionaries can be obtained with the len()
```{python eval=F}
# Tuples are enclosed in paranthesis
mytuple=(1,3,7,6,"test")
print(mytuple)
# Lists are enclosed in square bracket
mylist = [1, 2, 7, 4, 12 ]
#Dictionary - These are similar to name-value pairs
mydict={'Name':'Ganesh','Age':54,'Occupation':'Engineer'}
print(mydict)
print(mydict['Age'])
# No of elements in tuples, lists and dictionaries can be got with len()
print("Length of tuple=",len(mytuple))
print("Length of list =", len(mylist))
print("Length of dictionary =",len(mydict))
```

##### Lists
```{python}
# empty list 
empty = [] 
# empty = list()
empty.append(23)
empty.append(45)
empty

# list slicing [start:end:stride] 
weekdays = ['mon','tues','wed','thurs','fri'] 
# weekdays[0] # element 0 
# weekdays[0:3] # elements 0, 1, 2 
# weekdays[:3] # elements 0, 1, 2 
# weekdays[3:] # elements 3, 4 
# weekdays[-1] # last element (element 4) 
# weekdays[::2] # every 2nd element (0, 2, 4) 
# weekdays[::-1] # backwards (4, 3, 2, 1, 0)

# sort a list 
weekdays.sort() 
weekdays.sort(reverse=True) # sort in reverse 
weekdays.sort(key=len) # sort by a key
# conatenate +, replicate * 
[1, 2, 3] + [4, 5, 6]
["a"] * 2 + ["b"] * 3

```

##### Tuples
```{python eval=F}
# create a tuple 
digits = (0, 1, 'two') # create a tuple directly 
digits = tuple([0, 1, 'two']) # create a tuple from a list 
# examine a tuple 
digits[2] # returns 'two' 
len(digits) # returns 3 
digits.count(0) # counts the number of instances of that value (1) 
digits.index(1) # returns the index of the first instance of that value (1)
```

##### Dictionaries
```{python eval=F} 
# create a dictionary (two ways) 
family = {'dad':'homer', 'mom':'marge', 'size':6} 
family = dict(dad='homer', mom='marge', size=6)

# examine a dictionary 
family['dad'] # returns 'homer' 
len(family) # returns 3 
family.keys() # returns list: ['dad', 'mom', 'size'] 
family.values() # returns list: ['homer', 'marge', 6] 
family.items() # returns list of tuples: 
# [('dad', 'homer'), ('mom', 'marge'), ('size', 6)] 
'mom' in family # returns True 
'marge' in family # returns False (only checks keys)

```
#### Set : 집합 - list 와 달리 중복과 순서가 없음
```{python eval=F}
# create a set 
languages = {'python', 'r', 'java'} # create a set directly 
snakes = set(['cobra', 'viper', 'python']) # create a set from a list
# examine a set 
len(languages) # returns 3 
'python' in languages # returns True
# set operations 1
languages & snakes # returns intersection: {'python'} 
languages | snakes # returns union: {'cobra', 'r', 'java', 'viper', 'python'} 
languages - snakes # returns set difference: {'r', 'java'} 
snakes - languages # returns set difference: {'cobra', 'viper'}
# set operations 2
s1 = {1,2,3,4,5}
s2 = {2,4,6}
print(s1.intersection(s2)) # 교집합 {2, 4}
print(s1.union(s2)) # 합집합
{1, 2, 3, 4, 5, 6}
print(s1.difference(s2)) # 차집합
{1, 3, 5}
```

#### Conditional statements (조건문)
```{python eval=F}
x = 3 
# if statement 
if x > 0: 
    print('positive')
# if/else statement 
if x > 0: 
    print('positive') 
else: 
    print('zero or negative')
# if/elif/else statement 
if x > 0: 
    print('positive') 
elif x == 0: 
    print('zero')
else: 
    print('negative')
```

#### Loops (반복문)
```{python eval=F}
# range returns a list of integers 
range(0, 3) # returns [0, 1, 2]: includes first value but excludes second value 
range(0, 5, 2) # returns [0, 2, 4]: third argument specifies the 'stride'
fruits = ['apple', 'banana', 'cherry']
for fruit in fruits: 
    print(fruit.upper()) 
for fruit in fruits: 
    if fruit == 'banana': 
        print("Found the banana!") 
        break # exit the loop and skip the 'else' block 
    else: 
        # this block executes ONLY if the for loop completes without hitting 'break' 
        print("Can't find the banana")
count = 0 
while count < 5: 
    print("This will print 5 times") 
    count += 1 # equivalent to 'count = count + 1'
```

#### Functions
```{python eval=F}
# define a function with no arguments and no return values 
def print_text(): 
    print('this is text')
# call the function 
print_text()
# define a function with one argument and no return values 
def print_this(x): 
    print(x)
# call the function 
print_this(3) # prints 3 
n = print_this(3) # prints 3, but doesn't assign 3 to n 
# because the function has no return statement
# define a function with one argument and one return value 
def square_this(x): 
    return x ** 2
# call the function 
square_this(3) # prints 9 
var = square_this(3) # assigns 9 to var, but does not print 9

# default arguments 
def power_this(x, power=2): 
    return x ** power
power_this(2) # 4 
power_this(2, 3) # 8
# return two values from a single function 
def min_max(nums): 
    return min(nums), max(nums)
# return values can be assigned to a single variable as a tuple
nums = [1, 2, 3] 
min_max_num = min_max(nums) # min_max_num = (1, 3)

```

#### Functions – lambda
• Lambda operations all you to create small anonymous function which
computes something
```{python eval=F}
# operations on list
a = [5,2,3,1,7]
b = [1,5,4,6,8]
# Create a lambda function to add 2 numbers 
add_fct = lambda x,y:x+y
add_fct(a,b)
# Add all elements of lists a and b 
print(list(map(add_fct, a,b))) # [6, 7, 7, 7, 15]
```
Ref: Practical machine learning with R and Python:3rd ed., Tinniam V Ganesh

#### Object oriented programming(OOP) 
```{python}
import math
# Inheritance + Encapsulation 
class Square(): 
    def __init__(self, width): 
        self.width = width
    def area(self): 
        return self.width ** 2
class Disk(): 
    def __init__(self, radius): 
        self.radius = radius
    def area(self): 
        return math.pi * self.radius ** 2
shapes = [Square(2), Disk(3)]
# Polymorphism 
print([s.area() for s in shapes])

a= Square(2)
a.area()

```

#### Read text file using pandas 
```{python eval=F}
# 데이터가 없어서 실행할 수 없음

import os
import pandas as pd
import matplotlib.pyplot as plt
# Set the current working directory 
os.chdir(“c:/data/pydata”) 
os.getcwd() # 'c:\\data\\pydata'
# data = pd_read.csv(‘c:/data/pydata/bmi.csv’)
data = pd.read_csv(“bmi.csv”) 
data.head()
Out[13]: 
height weight
0 181 78
1 161 49
2 170 52
3 160 53
4 158 50
weig = data[‘weight’]
heig = data[‘height’] 
bmi = weig/(heig/100)**2
plt.scatter(heig, weig)
plt.show()
```


#### Read Excel file using pandas 
```{python eval=F}
# 실행되지 않음 
import os
import pandas as pd
import matplotlib.pyplot as plt
# Set the current working directory 
os.chdir('data')
os.getcwd() # 'c:\\data\\pydata'
beer = pd.read_excel('ex9-2.xlsx', sheet_name='ex9-2')
beer.head()
```

#### Numpy
NumPy is one of the most fundamental package for scientific computing 
with Python. Numpy includes the support for handling large, multidimensional
arrays and matrices, along with a large collection of highlevel
mathematical functions to operate on these arrays.
```{python}
import numpy as np
#Create a 1d numpy array
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
print(arr1)
```
Python의 기본 자료구조
- list / tuple / dictionary / set
: The Python languge was not initially 
designed for numerical computing
: 1995 matrix-sig group
: 2006 numpy


```{python}
# Create numpy array in a single line
import numpy as np
arr1= np.array([6, 7.5, 8, 0, 1])
#Print the array
print(arr1)
### 2D array
#Create a 2d numpy array
import numpy as np
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
# Print the 2d array
print(arr2)
```