# 2강
- 단변량 그래프
- Rmd 파일에서는 dev.new()/ def.off() 함수를 사용하지 않는다.


## R 막대그림 및 원그림
```{r}
survey = read.csv('./data/survey.csv')
edu_tb = table(survey$edu)
edu_tb
rownames(edu_tb) = c("무학","초졸", "중졸","고졸","대졸")
barplot(edu_tb)

# dev.new()
pie(edu_tb, main="교육정도 원그림")
# dev.off()


# 겹친막대그림
sex_edu = list(survey$sex, survey$edu)
sex_edu_tb = table(sex_edu)
sex_edu_tb
barplot(sex_edu_tb, legend.text=rownames(sex_edu_tb), col=c("red","blue"))
title("Stacked Barplot")

# 한 화면에 여러개의 그래프 그리기

# 남녀별로 교육정도의 원그림 그리기
par(mfrow=c(1,2))
pie(sex_edu_tb[1,])
title("Education of Male")

pie(sex_edu_tb[2,]) 
title("Education of Female")

par(mfrow=c(1,1))
# R 히스토그램
hist(survey$salary)
# R 줄기-잎 그림
stem(survey$salary)
stem(survey$salary, scale=2)

# 상자그림
boxplot(salary ~ sex, data=survey)
title("Boxplot of Salary")

```

## 파이썬 막대그림 및 원그림

```{python}
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
# 데이터 읽기
survey = pd.read_csv("./data/survey.csv")
# 빈도수 구하기
edu_freq = pd.crosstab(index=survey.edu, columns='count')
edu_freq
# 케이스 라벨 지정하기
edu_freq.index = ["none", "elementary", "middle", "high", "college"]

# 막대그림 그리기
plt.bar(edu_freq.index, edu_freq["count"])
# 원그림 그리기
plt.pie(edu_freq["count"], labels=edu_freq.index) 

# (edu, sex) 분할표 구하기
edu_sex_tb = pd.crosstab(index=survey.edu, columns=survey.sex)
# 케이스 및 변수이름 지정하기
edu_sex_tb.index = ["none", "elementary", "middle", "high", "college"]
edu_sex_tb.columns = ["Male", "Female"]

# 겹친 막대그림 그리기
edu_sex_tb.plot.bar(stacked=True)

# 한화면에 여러개의 그래프 그리기
plt.figure()
plt.subplot(121) # 121 1행 2열 1번째
plt.bar(edu_freq.index, edu_freq["count"])
plt.subplot(122) # 121 1행 2열 2번째
plt.pie(edu_freq["count"], labels=edu_freq.index) 

import matplotlib.pyplot as plt
# 히스토그램 그리기
plt.hist(survey["salary"])

# 줄기-잎 그림 그리기
# pip3 install stemgraphic (in DOS prompt)
import stemgraphic
stemgraphic.stem_graphic(survey.salary, scale=50)

import seaborn as sns
sns.boxplot(x="sex", y="salary", data=survey)

```

# 이변량 그래프

## R 이변량 그래프
```{r}
# plot using lines
plot(co2)
lines(smooth(co2),col="BLUE")
# plot of mathematical functions
x <- seq(0, 20, 0.1) 
y <- exp(-x/10)*cos(2*x) 
plot(x,y,type="l") 

# Bivariate boxplot
install.packages("HSAUR2")
library(HSAUR2)
install.packages("MVA")
library(MVA)
data(USairpollution)
head(USairpollution, 3)

x = USairpollution[, c(3,4)]
bvbox(x, xlab="manu", ylab="popul", pch=19)
title("Bivariate Boxplot")
identify(x)
rownames(x)[c(7,9,14,30)]

# Bubble plot
plot(wind~temp, data=USairpollution, pch=9)
# symbols(USairpollution$temp, USairpollution$wind, USairpollution$circle=SO2,
# inches=0.5, add=T)) 
with(USairpollution, symbols(temp, wind, circle=SO2, inches=0.5, add=T))
title("Bubble plot")


```

## 파이썬 이변량 그래프
```{python}
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
# 데이터 읽기
co2 = pd.read_csv("./data/co2.csv")
co2.head(2)
# 변수이름 지정하기
co2.columns = ["seq", "x"]
co2.head(2)

# 데이터 읽기
USairpollution = pd.read_csv("./data/USairpollution.csv")
USairpollution.head(3)

# SO2 변숫값 * 5
USairpollution["SO2"] = USairpollution["SO2"] * 5 # * 5는 버블의 크기가 작아서 크기를 키우기위해서 사용
# 버블차트 그리기
plt.scatter('temp', 'wind', s='SO2', alpha=0.9, data=USairpollution)
plt.xlabel("temp", size=16)
plt.ylabel("wind", size=16)
plt.title("Bubble plot")

```

# 다차원 그래프

## R 산점도 행렬
```{r}
social = read.table("./data/social.txt", header=T)
head(social, 3)

pairs(social)
round(cor(social, use="complete.obs"), 3)

# 별그림
social2 = social[, -1]
year = social[,1]
rownames(social2) = year
stars(social2)

# install.packages("aplpack")
library(aplpack) 
# faces(social2, face.type=0, na.rm=TRUE) 
faces(social2, face.type=0)

```

## 파이썬 산점도 행렬
```{python}

import pandas as pd
# 데이터 읽기
social = pd.read_csv("./data/social.csv")
# (행의 수, 열의 수)
social.shape

# seaborn을 이용하여 산점도행렬 그리기
import seaborn as sns
sns.pairplot(social)
# 상관계수 행렬 구하기 – 소수점 이하 3자리 반올림
round(social.corr(), 3)

import seaborn as sns
# seaborn에 내장된 iris 데이터 가져오기
iris = sns.load_dataset("iris")
iris.head()

# species로 구분된 산점도행렬 그리기 - 대각선은 각 그룹별 분포
sns.pairplot(iris, hue='species', height=2.5)


```