% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{lmodern}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same} % disable monospaced font for URLs
\hypersetup{
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\author{}
\date{\vspace{-2.5em}}

\begin{document}

\hypertarget{uxb370uxc774uxd130uxb9c8uxc774uxb2dd-uxcd9cuxc11duxc218uxc5c5-uxacfcuxc81c}{%
\section{데이터마이닝 출석수업
과제}\label{uxb370uxc774uxd130uxb9c8uxc774uxb2dd-uxcd9cuxc11duxc218uxc5c5-uxacfcuxc81c}}

\hypertarget{section}{%
\subsection{1}\label{section}}

\hypertarget{section-1}{%
\subsection{2}\label{section-1}}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# 와인 데이터 파일 읽기}
\NormalTok{wine }\OtherTok{=} \FunctionTok{read.csv}\NormalTok{(}\StringTok{"./data/winequalityCLASS.csv"}\NormalTok{, }\AttributeTok{header=}\ConstantTok{TRUE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\hypertarget{section-2}{%
\subsubsection{2-①}\label{section-2}}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# binomial(link = "logit")이 기본값으로 생략할 수 있다.}
\NormalTok{fit\_alcohol }\OtherTok{=} \FunctionTok{glm}\NormalTok{(quality }\SpecialCharTok{\textasciitilde{}}\NormalTok{ alcohol, }\AttributeTok{family =}\NormalTok{ binomial, }\AttributeTok{data =}\NormalTok{ wine)}
\FunctionTok{summary}\NormalTok{(fit\_alcohol)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## glm(formula = quality ~ alcohol, family = binomial, data = wine)
## 
## Coefficients:
##              Estimate Std. Error z value Pr(>|z|)    
## (Intercept) -11.87055    0.85910  -13.82   <2e-16 ***
## alcohol       1.17118    0.08425   13.90   <2e-16 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 1647.5  on 1193  degrees of freedom
## Residual deviance: 1381.5  on 1192  degrees of freedom
## AIC: 1385.5
## 
## Number of Fisher Scoring iterations: 4
\end{verbatim}

\begin{itemize}
\tightlist
\item
  로지스틱 회귀모형은 다음과 같다.

  \begin{itemize}
  \tightlist
  \item
    \(\ln({p \over 1-p}) = -11.870549 + 1.171183 * alcohol\)
  \end{itemize}
\item
  alcohol이 1단위 증가할 때마다 오즈비는 1.17배가 증가된다.
\item
  AIC는 1385.5이다.
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{p }\OtherTok{=} \FunctionTok{predict}\NormalTok{(fit\_alcohol, }\AttributeTok{newdata=}\NormalTok{wine, }\AttributeTok{type=}\StringTok{"response"}\NormalTok{)}
\NormalTok{cutoff }\OtherTok{=} \FloatTok{0.5}
\NormalTok{yhat }\OtherTok{=} \FunctionTok{ifelse}\NormalTok{(p}\SpecialCharTok{\textgreater{}}\NormalTok{cutoff, }\DecValTok{1}\NormalTok{, }\DecValTok{0}\NormalTok{)}
\NormalTok{tab }\OtherTok{=} \FunctionTok{table}\NormalTok{(wine}\SpecialCharTok{$}\NormalTok{quality, yhat, }\AttributeTok{dnn=}\FunctionTok{c}\NormalTok{(}\StringTok{"Observed"}\NormalTok{, }\StringTok{"Predicted"}\NormalTok{))}
\FunctionTok{print}\NormalTok{(tab)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##         Predicted
## Observed   0   1
##        0 409 140
##        1 204 441
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{paste}\NormalTok{(}\StringTok{"정확도 :"}\NormalTok{, }\FunctionTok{round}\NormalTok{( }\FunctionTok{sum}\NormalTok{(}\FunctionTok{diag}\NormalTok{(tab)) }\SpecialCharTok{/}\FunctionTok{sum}\NormalTok{(tab),}\DecValTok{3}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "정확도 : 0.712"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{paste}\NormalTok{(}\StringTok{"민감도 :"}\NormalTok{, }\FunctionTok{round}\NormalTok{(tab[}\DecValTok{2}\NormalTok{,}\DecValTok{2}\NormalTok{]}\SpecialCharTok{/}\FunctionTok{sum}\NormalTok{(tab[}\DecValTok{2}\NormalTok{,]),}\DecValTok{3}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "민감도 : 0.684"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{paste}\NormalTok{(}\StringTok{"특이도 :"}\NormalTok{, }\FunctionTok{round}\NormalTok{(tab[}\DecValTok{1}\NormalTok{,}\DecValTok{1}\NormalTok{]}\SpecialCharTok{/}\FunctionTok{sum}\NormalTok{(tab[}\DecValTok{1}\NormalTok{,]),}\DecValTok{3}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "특이도 : 0.745"
\end{verbatim}

\hypertarget{section-3}{%
\subsubsection{2-②}\label{section-3}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{fit\_sulphates }\OtherTok{=} \FunctionTok{glm}\NormalTok{(quality }\SpecialCharTok{\textasciitilde{}}\NormalTok{ sulphates, }\AttributeTok{family =}\NormalTok{ binomial, }\AttributeTok{data =}\NormalTok{ wine)}
\FunctionTok{summary}\NormalTok{(fit\_sulphates)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## glm(formula = quality ~ sulphates, family = binomial, data = wine)
## 
## Coefficients:
##             Estimate Std. Error z value Pr(>|z|)    
## (Intercept)  -4.5135     0.3984  -11.33   <2e-16 ***
## sulphates     7.4757     0.6374   11.73   <2e-16 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 1647.5  on 1193  degrees of freedom
## Residual deviance: 1474.6  on 1192  degrees of freedom
## AIC: 1478.6
## 
## Number of Fisher Scoring iterations: 3
\end{verbatim}

\begin{itemize}
\tightlist
\item
  로지스틱 회귀모형은 다음과 같다.

  \begin{itemize}
  \tightlist
  \item
    \(\ln({p \over 1-p}) = -4.5135 + 7.4757 * sulphates\)
  \end{itemize}
\item
  sulphates이 1단위 증가할 때마다 오즈비는 7.48배가 증가된다.
\item
  AIC는 1478.6이다.
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{p }\OtherTok{=} \FunctionTok{predict}\NormalTok{(fit\_sulphates, }\AttributeTok{newdata=}\NormalTok{wine, }\AttributeTok{type=}\StringTok{"response"}\NormalTok{)}
\NormalTok{cutoff }\OtherTok{=} \FloatTok{0.5}
\NormalTok{yhat }\OtherTok{=} \FunctionTok{ifelse}\NormalTok{(p}\SpecialCharTok{\textgreater{}}\NormalTok{cutoff, }\DecValTok{1}\NormalTok{, }\DecValTok{0}\NormalTok{)}
\NormalTok{tab }\OtherTok{=} \FunctionTok{table}\NormalTok{(wine}\SpecialCharTok{$}\NormalTok{quality, yhat, }\AttributeTok{dnn=}\FunctionTok{c}\NormalTok{(}\StringTok{"Observed"}\NormalTok{, }\StringTok{"Predicted"}\NormalTok{))}
\FunctionTok{print}\NormalTok{(tab)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##         Predicted
## Observed   0   1
##        0 345 204
##        1 220 425
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{paste}\NormalTok{(}\StringTok{"정확도 :"}\NormalTok{, }\FunctionTok{round}\NormalTok{( }\FunctionTok{sum}\NormalTok{(}\FunctionTok{diag}\NormalTok{(tab)) }\SpecialCharTok{/}\FunctionTok{sum}\NormalTok{(tab),}\DecValTok{3}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "정확도 : 0.645"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{paste}\NormalTok{(}\StringTok{"민감도 :"}\NormalTok{, }\FunctionTok{round}\NormalTok{(tab[}\DecValTok{2}\NormalTok{,}\DecValTok{2}\NormalTok{]}\SpecialCharTok{/}\FunctionTok{sum}\NormalTok{(tab[}\DecValTok{2}\NormalTok{,]),}\DecValTok{3}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "민감도 : 0.659"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{paste}\NormalTok{(}\StringTok{"특이도 :"}\NormalTok{, }\FunctionTok{round}\NormalTok{(tab[}\DecValTok{1}\NormalTok{,}\DecValTok{1}\NormalTok{]}\SpecialCharTok{/}\FunctionTok{sum}\NormalTok{(tab[}\DecValTok{1}\NormalTok{,]),}\DecValTok{3}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "특이도 : 0.628"
\end{verbatim}

\hypertarget{section-4}{%
\subsubsection{2-③}\label{section-4}}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Fitting a logistic regression model}
\NormalTok{fit.all }\OtherTok{=} \FunctionTok{glm}\NormalTok{(quality }\SpecialCharTok{\textasciitilde{}}\NormalTok{ ., }\AttributeTok{family =}\NormalTok{ binomial, }\AttributeTok{data =}\NormalTok{ wine)}
\NormalTok{fit.step }\OtherTok{=} \FunctionTok{step}\NormalTok{(fit.all, }\AttributeTok{direction=}\StringTok{"both"}\NormalTok{) }\CommentTok{\# stepwise vaiable selection}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Start:  AIC=1249.78
## quality ~ fixed + volatile + citric + residsugar + chlorides + 
##     freeSD + totalSD + density + pH + sulphates + alcohol
## 
##              Df Deviance    AIC
## - density     1   1225.8 1247.8
## - residsugar  1   1226.0 1248.0
## - fixed       1   1226.2 1248.2
## <none>            1225.8 1249.8
## - chlorides   1   1228.2 1250.2
## - pH          1   1228.6 1250.6
## - freeSD      1   1230.5 1252.5
## - citric      1   1232.4 1254.4
## - totalSD     1   1237.1 1259.1
## - volatile    1   1247.3 1269.3
## - alcohol     1   1275.1 1297.1
## - sulphates   1   1283.4 1305.4
## 
## Step:  AIC=1247.84
## quality ~ fixed + volatile + citric + residsugar + chlorides + 
##     freeSD + totalSD + pH + sulphates + alcohol
## 
##              Df Deviance    AIC
## - residsugar  1   1226.0 1246.0
## - fixed       1   1227.4 1247.4
## <none>            1225.8 1247.8
## - chlorides   1   1228.2 1248.2
## - pH          1   1229.4 1249.4
## + density     1   1225.8 1249.8
## - freeSD      1   1230.5 1250.5
## - citric      1   1232.4 1252.4
## - totalSD     1   1237.2 1257.2
## - volatile    1   1247.5 1267.5
## - sulphates   1   1288.6 1308.6
## - alcohol     1   1347.2 1367.2
## 
## Step:  AIC=1246.05
## quality ~ fixed + volatile + citric + chlorides + freeSD + totalSD + 
##     pH + sulphates + alcohol
## 
##              Df Deviance    AIC
## - fixed       1   1227.5 1245.5
## <none>            1226.0 1246.0
## - chlorides   1   1228.8 1246.8
## + residsugar  1   1225.8 1247.8
## - pH          1   1229.9 1247.9
## + density     1   1226.0 1248.0
## - freeSD      1   1230.8 1248.8
## - citric      1   1232.6 1250.6
## - totalSD     1   1238.7 1256.7
## - volatile    1   1248.1 1266.1
## - sulphates   1   1289.2 1307.2
## - alcohol     1   1351.7 1369.7
## 
## Step:  AIC=1245.45
## quality ~ volatile + citric + chlorides + freeSD + totalSD + 
##     pH + sulphates + alcohol
## 
##              Df Deviance    AIC
## <none>            1227.5 1245.5
## - chlorides   1   1229.8 1245.8
## + fixed       1   1226.0 1246.0
## + density     1   1226.8 1246.8
## + residsugar  1   1227.4 1247.4
## - freeSD      1   1232.5 1248.5
## - citric      1   1232.7 1248.7
## - pH          1   1238.3 1254.3
## - totalSD     1   1241.8 1257.8
## - volatile    1   1248.2 1264.2
## - sulphates   1   1295.2 1311.2
## - alcohol     1   1351.9 1367.9
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{fit.step}\SpecialCharTok{$}\NormalTok{anova}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##           Step Df   Deviance Resid. Df Resid. Dev      AIC
## 1              NA         NA      1182   1225.779 1249.779
## 2    - density  1 0.05882012      1183   1225.838 1247.838
## 3 - residsugar  1 0.21095811      1184   1226.049 1246.049
## 4      - fixed  1 1.40549703      1185   1227.454 1245.454
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{summary}\NormalTok{(fit.step)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## glm(formula = quality ~ volatile + citric + chlorides + freeSD + 
##     totalSD + pH + sulphates + alcohol, family = binomial, data = wine)
## 
## Coefficients:
##              Estimate Std. Error z value Pr(>|z|)    
## (Intercept) -3.598450   2.246265  -1.602 0.109162    
## volatile    -2.625798   0.587804  -4.467 7.93e-06 ***
## citric      -1.304024   0.570926  -2.284 0.022369 *  
## chlorides   -8.134165   5.330701  -1.526 0.127033    
## freeSD       0.024636   0.010981   2.244 0.024862 *  
## totalSD     -0.014548   0.003919  -3.712 0.000205 ***
## pH          -2.029157   0.620285  -3.271 0.001070 ** 
## sulphates    5.609315   0.722816   7.760 8.47e-15 ***
## alcohol      0.933382   0.091576  10.192  < 2e-16 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 1647.5  on 1193  degrees of freedom
## Residual deviance: 1227.5  on 1185  degrees of freedom
## AIC: 1245.5
## 
## Number of Fisher Scoring iterations: 4
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Making predictions}
\NormalTok{p }\OtherTok{=} \FunctionTok{predict}\NormalTok{(fit.step, }\AttributeTok{newdata=}\NormalTok{wine, }\AttributeTok{type=}\StringTok{"response"}\NormalTok{) }\CommentTok{\# prediction}
\NormalTok{cutoff }\OtherTok{=} \FloatTok{0.5} \CommentTok{\#cutoff}
\NormalTok{yhat }\OtherTok{=} \FunctionTok{ifelse}\NormalTok{(p }\SpecialCharTok{\textgreater{}}\NormalTok{ cutoff, }\DecValTok{1}\NormalTok{, }\DecValTok{0}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Evaluation}
\NormalTok{tab }\OtherTok{=} \FunctionTok{table}\NormalTok{(wine}\SpecialCharTok{$}\NormalTok{quality, yhat, }\AttributeTok{dnn=}\FunctionTok{c}\NormalTok{(}\StringTok{"Observed"}\NormalTok{,}\StringTok{"Predicted"}\NormalTok{))}
\FunctionTok{print}\NormalTok{(tab)              }\CommentTok{\# confusion matrix}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##         Predicted
## Observed   0   1
##        0 402 147
##        1 150 495
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{sum}\NormalTok{(}\FunctionTok{diag}\NormalTok{(tab))}\SpecialCharTok{/}\FunctionTok{sum}\NormalTok{(tab) }\CommentTok{\# accuracy(정분류)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.7512563
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{tab[}\DecValTok{2}\NormalTok{,}\DecValTok{2}\NormalTok{]}\SpecialCharTok{/}\FunctionTok{sum}\NormalTok{(tab[}\DecValTok{2}\NormalTok{,])   }\CommentTok{\# sensitivity(민감도)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.7674419
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{tab[}\DecValTok{1}\NormalTok{,}\DecValTok{1}\NormalTok{]}\SpecialCharTok{/}\FunctionTok{sum}\NormalTok{(tab[}\DecValTok{1}\NormalTok{,])   }\CommentTok{\# specificity(특이도)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.7322404
\end{verbatim}

\hypertarget{section-5}{%
\subsection{2-①②③}\label{section-5}}

\end{document}
