---
title: "13강 선형회귀모형 실습"
author: "이재용"
date: "2022.08.10"
output:
  html_document:
    number_sections: yes
    theme: cosmo
    toc: yes
    toc_depth: 2
    toc_float: yes
  github_document: 
    toc: yes
  pdf_document:
    toc: yes
    toc_depth: '2'
---


# 준비 

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = FALSE, error=TRUE)
Sys.setlocale(category = "LC_CTYPE", locale = "ko_KR.UTF-8")
library(ggplot2)
theme_set(theme_grey(base_family = "AppleGothic"))
```

```{r}
library(tidyverse) # ggplot2, dplyr 패키지들의 모임 
library(coda)
library(ggmcmc)
library(rstan)
#library(bridgesampling)

library(GGally) ## ggpairs
library(Hmisc) # hist를 데이터프레임에 적용할 수 있게 해준다. 이산형자료 요약에 좋은 describe가 있다. 
library(psych) # 연속형 자료 요약에 좋은 describe가 있다. 
library(forecast) # ggAcf, ggPacf
```
# 자료 읽기 

```{r}
adv = read.csv("Advertising.csv", header=T, sep=",")
adv = adv[,-1]
names(adv) = tolower(names(adv)) 
head(adv)
```

# 자료 탐색

광고자료의 분석에 앞서 자료에 대하여 기본적인 파악이 필요하다.

이를 탐색적 자료분석(EDA)라 부르며, 다음의 코드들을 통해 탐색적 자료분석을 진행한다.

## 1차원 자료 탐색 
```{r}
summary(adv) 
Hmisc::describe(adv)
psych::describe(adv)
hist(adv)

# ggplot(adv, aes(x=sales)) + geom_histogram(bins=10)
```

그림을 Rstudio pane에서 보고 싶으면 Rstudio의 콘솔에서 동일한 명령을 한번 더 수행한다. 

## 이차원 자료 탐색 
```{r}
#pairs(adv) 
cor(adv)
ggpairs(adv, aes(alpha = 0.4), color="darkred")
```

# 단순 선형 회귀 모형 
$$sales_i = \beta_0 + \beta_1 * tv_i + \epsilon, ~ \epsilon_i, ~ \epsilon_i \sim N(0,\sigma^2) $$
$$ \pi(\beta_0, \beta_1, \sigma^2)d\beta_0 d\beta_1 d\sigma^2 = \frac{1}{\sigma^2} d\beta_0 d\beta_1 d\sigma^2$$

```{r}
adv.lm1.code ="
data {
  int<lower=0> n;
  vector[n] tv;
  vector[n] sales;
}

parameters {
  real beta0;
  real beta1;
  real<lower=0> sigma;
}

model {
  for(i in 1:n) {
    sales[i] ~ normal(beta0 + beta1*tv[i], sigma);
  }
  
  target += 1/sigma^2;
}
"

data=list(n=dim(adv)[1], sales=adv$sales, tv=adv$tv)
```

```{r}
adv.lm1 = stan(model_code=adv.lm1.code, data=data, seed=1234567, chains=4, iter=5000, thin=1)
```

```{r}
print(adv.lm1)
```

```{r}
plot(adv.lm1, plotfun="dens")
```
```{r}
plot(adv.lm1, plotfun="trace")
```

```{r}
plot(adv.lm1, plotfun="ac")
```

# 중회귀 모형 
$$sales_i = \beta_0 + \beta_1 * tv_i + \beta_2*radio_i + \beta_3*newspaper_i + \epsilon, ~ \epsilon_i, ~ \epsilon_i \sim N(0,\sigma^2) $$
$$ \pi(\beta_0, \beta_1, \beta_2, \beta_3, \sigma^2)d\beta_0 d\beta_1 d\sigma^2 = \frac{1}{\sigma^2} d\beta_0 d\beta_1 d\beta_2 d\beta_3 d\sigma^2$$

```{r}
adv.lm2.code ="
data {
  int<lower=0> n;
  vector[n] tv;
  vector[n] radio;
  vector[n] newspaper;
  vector[n] sales;
}

parameters {
  real beta0;
  real beta1;
  real beta2;
  real beta3; 
  real<lower=0> sigma;
}

model {
  for(i in 1:n) {
    sales[i] ~ normal(beta0 + beta1*tv[i] + beta2*radio[i] + beta3*newspaper[i], sigma);
  }
  
  target += 1/sigma^2;
}
"

data=list(n=dim(adv)[1], sales=adv$sales, tv=adv$tv, radio=adv$radio, newspaper=adv$newspaper)
```

```{r}
adv.lm2 = stan(model_code=adv.lm2.code, data=data, seed=1234567, chains=4, iter=5000, thin=1)
```

```{r}
print(adv.lm2)
```

```{r}
plot(adv.lm2, plotfun="dens")
```
```{r}
plot(adv.lm2, plotfun="trace")
```

```{r}
plot(adv.lm2, plotfun="ac")
```
